import "./src/styles/index.scss"
import "./src/styles/layout.scss"
import "./src/styles/generics.scss"
import "./src/styles/header.scss"
import "./src/styles/footer.scss"
import "./src/styles/landing.scss"
import "./src/styles/heroImage.scss"
import "./src/styles/responsive.scss"
